let a = new Date();
console.log(a);
// console.log(typeof a);
let myDate = new Date('2/2/1990 20:12:40');
let b;
// b = a.getDay();
// b = a.getDate();
// b = a.getMonth();
// b = a.getFullYear();
// b = a.getTime();
// b = a.getHours();
// b = a.getMinutes();
// b = a.getSeconds();
// b = a.getMilliseconds();

b = myDate.setDate(15);
b = myDate.setMonth(0);
b = myDate.setFullYear(2040);
b = myDate.setHours(12);
b = myDate.setMinutes(30);
b = myDate.setSeconds(30);
console.log(myDate);